### ISSUE TITLE
Other projects worth including

### ISSUE THREAD

**Issue by kmusolff** [sheimo/awesome-lolbins-and-beyond#1]
Hi, 

Thanks for an awesome list, found some new cool sites for my collection here and I thought I'd share some other projects that can fit well here:
- https://filesec.io/ - file extensions used by attackers (credits mrd0x)
- https://malapi.io/ - WinAPI with nice descriptions and mapping (credits mrd0x)
- https://lots-project.com/ - sites useful for delivery and c2 (also mrd0x)
- https://evasions.checkpoint.com/ - evasions encyclopedia by check point research

Feel free to add these or not. Thanks again for sharing this.

**Comment by Mo1inari** [comment]
You could be interested to include these resources too:
https://sploitify.haxx.it/ 
https://lolad-project.github.io/
https://0xanalyst.github.io/Project-Lost/

**Comment by sheimo** [comment]
Added new resources based on recommendations. Thank you both for your suggestions!
